/* Generated automatically by the program `genconstants'
   from the machine description file `md'.  */

#ifndef GCC_INSN_CONSTANTS_H
#define GCC_INSN_CONSTANTS_H

#define REG_LS0 70
#define REG_LC1 67
#define REG_LS1 71
#define T1_REGNUM 6
#define RETURN_ADDR_REGNUM 1
#define REG_LC0 66
#define REG_LE0 68
#define REG_LE1 69
#define T0_REGNUM 5
#define VIT_REG 72

enum unspec {
  UNSPEC_LOAD_LOW = 0,
  UNSPEC_LOAD_HIGH = 1,
  UNSPEC_STORE_WORD = 2,
  UNSPEC_EH_RETURN = 3,
  UNSPEC_ADDRESS_FIRST = 4,
  UNSPEC_LOAD_GOT = 5,
  UNSPEC_TLS = 6,
  UNSPEC_TLS_LE = 7,
  UNSPEC_TLS_IE = 8,
  UNSPEC_TLS_GD = 9,
  UNSPEC_GPR_SAVE = 10,
  UNSPEC_GPR_RESTORE = 11,
  UNSPEC_BLOCKAGE = 12,
  UNSPEC_FENCE = 13,
  UNSPEC_FENCE_I = 14,
  UNSPEC_LSETUP_END = 15,
  UNSPEC_LS_LE_SET = 16,
  UNSPEC_LC_SET = 17,
  UNSPEC_VEC_PERM1 = 18,
  UNSPEC_VEC_PERM2 = 19,
  UNSPEC_VEC_PERM3 = 20,
  UNSPEC_VEC_PERM4 = 21,
  UNSPEC_VEC_PERM5 = 22,
  UNSPEC_VIT_MAX = 23,
  UNSPEC_VIT_SEL = 24,
  UNSPEC_ALLOC = 25,
  UNSPEC_NOP = 26,
  UNSPEC_READ_EVU = 27,
  UNSPEC_OFFSETED_READ = 28,
  UNSPEC_OFFSETED_READ_OMP = 29,
  UNSPEC_OMP_PULP_BARRIER = 30,
  UNSPEC_OMP_PULP_CRITICAL_START = 31,
  UNSPEC_OMP_PULP_CRITICAL_END = 32,
  UNSPEC_WRITESI_VOL = 33,
  UNSPEC_WRITESI = 34,
  UNSPEC_READSI_VOL = 35,
  UNSPEC_READSI = 36,
  UNSPEC_SPR_READ = 37,
  UNSPEC_SPR_WRITE = 38,
  UNSPEC_SPR_BIT_SET = 39,
  UNSPEC_SPR_BIT_CLR = 40,
  UNSPEC_COMPARE_AND_SWAP = 41,
  UNSPEC_SYNC_OLD_OP = 42,
  UNSPEC_SYNC_EXCHANGE = 43,
  UNSPEC_ATOMIC_STORE = 44,
  UNSPEC_MEMORY_BARRIER = 45
};
#define NUM_UNSPEC_VALUES 46
extern const char *const unspec_strings[];

#endif /* GCC_INSN_CONSTANTS_H */
